# Fail2Ban filter Ocean3inaBox management daemon

[INCLUDES]

before = common.conf

[Definition]

_daemon = Ocean3inaBox

failregex = Ocean3inaBox Management Daemon: Failed login attempt from ip <HOST> - timestamp .*
ignoreregex =
