	# Roundcube is available only on the dedicated webmail hostname.
	location / {
		alias /usr/local/lib/roundcubemail/;
		index index.php;
	}
	location ~ ^/(?:bin|config|logs|SQL|temp)/ {
		deny all;
	}
	location ~ ^/(?:CHANGELOG|INSTALL|LICENSE|README|UPGRADING)$ {
		deny all;
	}
		location ~ /\. {
			deny all;
		}
		location ~ ^/(.+\.php)$ {
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /usr/local/lib/roundcubemail/$1;
		fastcgi_pass php-fpm;
		client_max_body_size 128M;
	}
